// This file is auto-generated by @hey-api/openapi-ts

import { faker, type Faker } from '@faker-js/faker';

export type Options = {
    faker?: Faker;
    /**
     * Whether to include optional properties.
     * Provide a number between 0 and 1 to randomly include based on that probability.
     * @default true
     */
    includeOptional?: boolean | number;
    /**
     * Whether to use schema default values instead of generating fake data.
     * Provide a number between 0 and 1 to randomly use defaults based on that probability.
     * @default false
     */
    useDefault?: boolean | number;
};

const resolveCondition = (condition: boolean | number, faker: Faker): boolean => condition === true || typeof condition === 'number' && faker.datatype.boolean({ probability: condition });

const ensureFaker = (options?: Options): Faker => options?.faker ?? faker;

export const fakePet = (options?: Options) => ({
    id: ensureFaker(options).string.uuid(),
    name: ensureFaker(options).string.sample(),
    ...!resolveCondition(options?.includeOptional ?? true, ensureFaker(options)) ? {} : { age: ensureFaker(options).number.int({ min: 1, max: 120 }) }
});

export const fakeError = (options?: Options) => ({
    code: ensureFaker(options).number.int(),
    message: ensureFaker(options).string.sample()
});

export const fakeListPetsResponse = (options?: Options) => ensureFaker(options).helpers.multiple(() => fakePet(options));

export const fakeCreatePetResponse = (options?: Options) => fakePet(options);

export const fakeDeletePetResponse404 = (options?: Options) => fakeError(options);

export const fakeGetPetResponse200 = (options?: Options) => fakePet(options);

export const fakeGetPetResponse404 = (options?: Options) => fakeError(options);

export const fakeCreateJobResponse2Xx = (options?: Options) => fakePet(options);

export const fakeCreateJobResponse4Xx = (options?: Options) => fakeError(options);

export const fakeHealthCheckResponse = (options?: Options) => ensureFaker(options).string.sample();
