// This file is auto-generated by @hey-api/openapi-ts

import { faker, type Faker } from '@faker-js/faker';

import type { Animal, Cat, Circle, Dog, NullablePetOrTag, Pet, PetOrTag, PetWithOwner, Shape, Square, StringOrNumber, Tag } from '../types.gen';

export type Options = {
    faker?: Faker;
    /**
     * Whether to include optional properties.
     * Provide a number between 0 and 1 to randomly include based on that probability.
     * @default true
     */
    includeOptional?: boolean | number;
    /**
     * Whether to use schema default values instead of generating fake data.
     * Provide a number between 0 and 1 to randomly use defaults based on that probability.
     * @default false
     */
    useDefault?: boolean | number;
};

const ensureFaker = (options?: Options): Faker => options?.faker ?? faker;

export const fakePet = (options?: Options): Pet => ({
    name: ensureFaker(options).string.sample(),
    age: ensureFaker(options).number.int({ min: 1, max: 120 })
});

export const fakeTag = (options?: Options): Tag => ({
    id: ensureFaker(options).number.int(),
    label: ensureFaker(options).string.sample()
});

export const fakePetOrTag = (options?: Options): PetOrTag => ensureFaker(options).helpers.arrayElement([() => fakePet(options), () => fakeTag(options)])();

export const fakeStringOrNumber = (options?: Options): StringOrNumber => ensureFaker(options).helpers.arrayElement([() => ensureFaker(options).string.sample(), () => ensureFaker(options).number.float()])();

export const fakeNullablePetOrTag = (options?: Options): NullablePetOrTag => ensureFaker(options).helpers.arrayElement([
    () => fakePet(options),
    () => fakeTag(options),
    () => null
])();

export const fakePetWithOwner = (options?: Options): PetWithOwner => ({
    ...fakePet(options),
    ...{
        owner: ensureFaker(options).string.sample()
    }
});

export const fakeCircle = (options?: Options): Circle => ({
    kind: ensureFaker(options).string.sample(),
    radius: ensureFaker(options).number.float()
});

export const fakeSquare = (options?: Options): Square => ({
    kind: ensureFaker(options).string.sample(),
    side: ensureFaker(options).number.float()
});

export const fakeShape = (options?: Options): Shape => ensureFaker(options).helpers.arrayElement([() => ({
        ...fakeCircle(options),
        kind: 'Circle' as const
    }), () => ({
        ...fakeSquare(options),
        kind: 'Square' as const
    })])();

export const fakeDog = (options?: Options): Dog => ({
    type: ensureFaker(options).string.sample(),
    bark: ensureFaker(options).datatype.boolean()
});

export const fakeCat = (options?: Options): Cat => ({
    type: ensureFaker(options).string.sample(),
    purr: ensureFaker(options).datatype.boolean()
});

export const fakeAnimal = (options?: Options): Animal => ensureFaker(options).helpers.arrayElement([() => ({
        ...fakeDog(options),
        type: 'dog' as const
    }), () => ({
        ...fakeCat(options),
        type: 'cat' as const
    })])();
