import type { SymbolMeta } from '@hey-api/codegen-core';
import { fromRef } from '@hey-api/codegen-core';
import type { IR, SchemaExtractor, SchemaVisitor } from '@hey-api/shared';
import { childContext, pathToJsonPointer } from '@hey-api/shared';

import { $ } from '../../../../ts-dsl';
import { createFakerWalkerContext } from '../shared/faker-expr';
import type { ProcessorContext } from '../shared/processor';
import type { EmitTracking, Expression, FakerResult, FakerWalkerContext } from '../shared/types';
import type { FakerJsFakerPlugin } from '../types';
import { arrayToExpression } from './toAst/array';
import { booleanToExpression } from './toAst/boolean';
import { enumToExpression } from './toAst/enum';
import { numberToExpression } from './toAst/number';
import { objectToExpression } from './toAst/object';
import { stringToExpression } from './toAst/string';

export interface VisitorConfig {
  plugin: FakerJsFakerPlugin['Instance'];
  /** Optional schema extractor function. */
  schemaExtractor?: SchemaExtractor<ProcessorContext>;
  /** Shared tracking for conditional helper emission. */
  tracking: EmitTracking;
}

const FALLBACK_UNDEFINED: FakerResult = { expression: $('undefined'), usesFaker: false };

/**
 * Detect discriminator constraint schemas: objects where every property has a `const` value.
 * These are generated by the IR parser for discriminated unions.
 */
function isDiscriminatorConstraint(schema: IR.SchemaObject): boolean {
  if (schema.type !== 'object' || !schema.properties) return false;
  const props = schema.properties;
  return Object.keys(props).every((key) => props[key]!.const !== undefined);
}

export function createVisitor(
  config: VisitorConfig,
): SchemaVisitor<FakerResult, FakerJsFakerPlugin['Instance']> {
  const { schemaExtractor, tracking } = config;
  const fakerCtx: FakerWalkerContext = createFakerWalkerContext(tracking);

  return {
    applyModifiers(result) {
      return result;
    },
    array(schema, ctx, walk) {
      return {
        expression: arrayToExpression({ fakerCtx, schema, walk, walkerCtx: ctx }),
        usesFaker: true,
      };
    },
    boolean() {
      return {
        expression: booleanToExpression(fakerCtx),
        usesFaker: true,
      };
    },
    enum(schema) {
      const expression = enumToExpression(fakerCtx, schema);
      // Empty enums fall back to `undefined` literal — no faker usage
      const hasMembers = schema.items?.some(
        (item) => item.const !== undefined || item.type === 'null',
      );
      return { expression, usesFaker: !!hasMembers };
    },
    integer(schema) {
      return {
        expression: numberToExpression(fakerCtx, schema),
        usesFaker: true,
      };
    },
    intercept(schema, ctx, walk) {
      // const values are always emitted as literals
      if (schema.const !== undefined) {
        return { expression: $.fromValue(schema.const), usesFaker: false };
      }

      if (schemaExtractor && !schema.$ref) {
        const extracted = schemaExtractor({
          meta: {
            resource: 'definition',
            resourceId: pathToJsonPointer(fromRef(ctx.path)),
          },
          naming: ctx.plugin.config.definitions,
          path: fromRef(ctx.path),
          plugin: ctx.plugin,
          schema,
        });

        if (extracted !== schema) {
          return walk(extracted, ctx);
        }
      }
    },
    intersection(items, schemas) {
      if (items.length === 0) {
        return FALLBACK_UNDEFINED;
      }
      if (items.length === 1) {
        return items[0]!;
      }

      // Check if all items are "spreadable" (produce object-like values)
      const allSpreadable = schemas.every(
        (s) => s.$ref || s.type === 'object' || (s.items && s.logicalOperator),
      );

      if (!allSpreadable) {
        return items[0]!;
      }

      // Reorder so discriminator constraint objects (all-const properties) are spread last
      const indexed = items.map((item, i) => ({ item, schema: schemas[i]! }));
      const regular: typeof indexed = [];
      const discriminators: typeof indexed = [];

      for (const entry of indexed) {
        if (isDiscriminatorConstraint(entry.schema)) {
          discriminators.push(entry);
        } else {
          regular.push(entry);
        }
      }

      const obj = $.object().pretty();
      // Spread regular items first
      for (const { item } of regular) {
        obj.spread(item.expression);
      }
      // Emit discriminator constraint properties directly with `as const` to preserve literal types
      for (const { schema } of discriminators) {
        for (const key of Object.keys(schema.properties!)) {
          obj.prop(key, $($.fromValue(schema.properties![key]!.const)).as('const'));
        }
      }

      return {
        expression: obj,
        usesFaker: items.some((item) => item.usesFaker),
      };
    },
    never() {
      return FALLBACK_UNDEFINED;
    },
    null() {
      return { expression: $.fromValue(null), usesFaker: false };
    },
    number(schema) {
      return {
        expression: numberToExpression(fakerCtx, schema),
        usesFaker: true,
      };
    },
    object(schema, ctx, walk) {
      return {
        expression: objectToExpression({ fakerCtx, schema, walk, walkerCtx: ctx }),
        usesFaker: true,
      };
    },
    postProcess(result, schema) {
      // resolveCondition(options?.useDefault ?? false, faker) ? <default> : <faker>
      if (schema.default !== undefined && result.usesFaker) {
        tracking.needsResolveCondition = true;
        const condition = $('resolveCondition').call(
          $.binary($(fakerCtx.optionsId).attr('useDefault').optional(), '??', $.literal(false)),
          fakerCtx.fakerAccessor,
        );
        const defaultExpr = $.fromValue(schema.default);
        return {
          expression: $.ternary(condition).do(defaultExpr).otherwise(result.expression),
          usesFaker: true,
        };
      }
      return result;
    },
    reference($ref, _schema, ctx) {
      const query: SymbolMeta = {
        category: 'schema',
        resource: 'definition',
        resourceId: $ref,
        tool: 'faker',
      };

      const refSymbol = ctx.plugin.referenceSymbol(query);

      return {
        expression: $(refSymbol).call(fakerCtx.optionsId),
        usesFaker: true,
      };
    },
    string(schema) {
      return {
        expression: stringToExpression(fakerCtx, schema),
        usesFaker: true,
      };
    },
    tuple(schema, ctx, walk) {
      const elements: Array<Expression> = [];
      let anyChildUsesFaker = false;
      for (let i = 0; i < (schema.items?.length ?? 0); i++) {
        const item = schema.items![i]!;
        const result = walk(item, childContext(ctx, 'items', i));
        elements.push(result.expression);
        if (result.usesFaker) anyChildUsesFaker = true;
      }
      return { expression: $.array(...elements), usesFaker: anyChildUsesFaker };
    },
    undefined() {
      return FALLBACK_UNDEFINED;
    },
    union(items, schemas) {
      if (items.length === 0) {
        return FALLBACK_UNDEFINED;
      }
      if (items.length === 1) {
        return items[0]!;
      }

      const nullIndex = schemas.findIndex((s) => s.type === 'null');
      const hasNull = nullIndex !== -1;
      const nonNullItems = hasNull ? items.filter((_, i) => i !== nullIndex) : items;

      // Nullable union with exactly one non-null variant: simple ternary
      if (hasNull && nonNullItems.length === 1) {
        return {
          expression: $.ternary(fakerCtx.fakerAccessor.attr('datatype').attr('boolean').call())
            .do(nonNullItems[0]!.expression)
            .otherwise($.fromValue(null)),
          usesFaker: true,
        };
      }

      // Build thunks: () => expr for each variant (including null if present)
      const thunks = nonNullItems.map((item) => $.func().arrow().do($.return(item.expression)));
      if (hasNull) {
        thunks.push(
          $.func()
            .arrow()
            .do($.return($.fromValue(null))),
        );
      }

      // faker.helpers.arrayElement([() => v1(), () => v2(), ...])()
      return {
        expression: $(
          fakerCtx.fakerAccessor
            .attr('helpers')
            .attr('arrayElement')
            .call($.array(...thunks)),
        ).call(),
        usesFaker: true,
      };
    },
    unknown() {
      return FALLBACK_UNDEFINED;
    },

    void() {
      return FALLBACK_UNDEFINED;
    },
  };
}
