// This file is auto-generated by @hey-api/openapi-ts

import { http, type HttpHandler, HttpResponse, type HttpResponseResolver, type RequestHandlerOptions } from 'msw';

import type { GetFooResponses, PostFooData, PostFooResponses } from './types.gen';

const toMswPath = (path: string, baseUrl: string) => `${baseUrl}${path.replace(/\{([^}]+)\}/g, ':$1')}`;

const resolveToNull = () => new HttpResponse(null);

type ToResponseUnion<T> = {
    [K in Extract<keyof T, number>]: {
        status: K;
        result: T[K];
    };
}[Extract<keyof T, number>];

export type SingleHandlerFactories = {
    getFoo: (responseOrResolver: ToResponseUnion<GetFooResponses> | HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    postFoo: (responseOrResolver: ToResponseUnion<PostFooResponses> | HttpResponseResolver<never, PostFooData['body']>, options?: RequestHandlerOptions) => HttpHandler;
};

export type MswHandlerFactory = {
    of: SingleHandlerFactories;
};

export const createMswHandlerFactory = (config?: {
    baseUrl?: string;
}): MswHandlerFactory => {
    const baseUrl = config?.baseUrl ?? '';
    const of: SingleHandlerFactories = {
        getFoo: (res, options) => http.get(toMswPath('/foo', baseUrl), typeof res === 'object' && res.status ? () => HttpResponse.json(res.result ?? null, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options),
        postFoo: (res, options) => http.post(toMswPath('/foo', baseUrl), typeof res === 'object' && res.status ? () => HttpResponse.json(res.result ?? null, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options)
    };
    return { of };
};
