// This file is auto-generated by @hey-api/openapi-ts

import { faker, type Faker } from '@faker-js/faker';

import type { Bar, Foo } from '../types.gen';

export type Options = {
    faker?: Faker;
    includeOptional?: 'always' | 'random' | false;
    useDefault?: 'always' | 'random' | false;
};

const resolveCondition = (condition: 'always' | 'random' | false, faker: Faker): boolean => condition === 'always' || condition === 'random' && faker.datatype.boolean();

const ensureFaker = (options?: Options): Faker => options?.faker ?? faker;

export const fakeFoo = (options?: Options): Foo => ({
    name: ensureFaker(options).string.sample(),
    age: ensureFaker(options).number.int(),
    ...!resolveCondition(options?.includeOptional ?? 'always', ensureFaker(options)) ? {} : { active: ensureFaker(options).datatype.boolean() }
});

export const fakeBar = (options?: Options): Bar => ensureFaker(options).helpers.arrayElement(['baz', 'qux']);
