// This file is auto-generated by @hey-api/openapi-ts

import {
  http,
  type HttpHandler,
  HttpResponse,
  type HttpResponseResolver,
  type RequestHandlerOptions,
} from 'msw';

import type {
  AddPetData,
  AddPetResponses,
  CreateUserData,
  CreateUserResponses,
  CreateUsersWithListInputData,
  CreateUsersWithListInputResponses,
  DeleteOrderData,
  DeleteOrderResponses,
  DeletePetData,
  DeletePetResponses,
  DeleteUserData,
  DeleteUserResponses,
  FindPetsByStatusResponses,
  FindPetsByTagsResponses,
  GetInventoryResponses,
  GetOrderByIdData,
  GetOrderByIdResponses,
  GetPetByIdData,
  GetPetByIdResponses,
  GetUserByNameData,
  GetUserByNameResponses,
  LoginUserResponses,
  LogoutUserResponses,
  PlaceOrderData,
  PlaceOrderResponses,
  UpdatePetData,
  UpdatePetResponses,
  UpdatePetWithFormData,
  UpdatePetWithFormResponses,
  UpdateUserData,
  UpdateUserResponses,
  UploadFileData,
  UploadFileResponses,
} from './types.gen';

const toMswPath = (path: string, baseUrl: string) =>
  `${baseUrl}${path.replace(/\{([^}]+)\}/g, ':$1')}`;

const resolveToNull = () => new HttpResponse(null);

type ToResponseUnion<T> = {
  [K in Extract<keyof T, number>]: {
    result: T[K];
    status: K;
  };
}[Extract<keyof T, number>];

type StringifyPathParams<T> = {
  [K in keyof T]-?: string | ReadonlyArray<string>;
};

export type SingleHandlerFactories = {
  addPet: (
    responseOrResolver:
      | ToResponseUnion<AddPetResponses>
      | HttpResponseResolver<never, AddPetData['body']>,
    options?: RequestHandlerOptions,
  ) => HttpHandler;
  createUser: (
    responseOrResolver:
      | ToResponseUnion<CreateUserResponses>
      | HttpResponseResolver<never, CreateUserData['body']>,
    options?: RequestHandlerOptions,
  ) => HttpHandler;
  createUsersWithListInput: (
    responseOrResolver:
      | ToResponseUnion<CreateUsersWithListInputResponses>
      | HttpResponseResolver<never, CreateUsersWithListInputData['body']>,
    options?: RequestHandlerOptions,
  ) => HttpHandler;
  deleteOrder: (
    responseOrResolver?:
      | ToResponseUnion<DeleteOrderResponses>
      | HttpResponseResolver<StringifyPathParams<NonNullable<DeleteOrderData['path']>>, never>,
    options?: RequestHandlerOptions,
  ) => HttpHandler;
  deletePet: (
    responseOrResolver?:
      | ToResponseUnion<DeletePetResponses>
      | HttpResponseResolver<StringifyPathParams<NonNullable<DeletePetData['path']>>, never>,
    options?: RequestHandlerOptions,
  ) => HttpHandler;
  deleteUser: (
    responseOrResolver?:
      | ToResponseUnion<DeleteUserResponses>
      | HttpResponseResolver<StringifyPathParams<NonNullable<DeleteUserData['path']>>, never>,
    options?: RequestHandlerOptions,
  ) => HttpHandler;
  findPetsByStatus: (
    responseOrResolver: ToResponseUnion<FindPetsByStatusResponses> | HttpResponseResolver,
    options?: RequestHandlerOptions,
  ) => HttpHandler;
  findPetsByTags: (
    responseOrResolver: ToResponseUnion<FindPetsByTagsResponses> | HttpResponseResolver,
    options?: RequestHandlerOptions,
  ) => HttpHandler;
  getInventory: (
    responseOrResolver: ToResponseUnion<GetInventoryResponses> | HttpResponseResolver,
    options?: RequestHandlerOptions,
  ) => HttpHandler;
  getOrderById: (
    responseOrResolver:
      | ToResponseUnion<GetOrderByIdResponses>
      | HttpResponseResolver<StringifyPathParams<NonNullable<GetOrderByIdData['path']>>, never>,
    options?: RequestHandlerOptions,
  ) => HttpHandler;
  getPetById: (
    responseOrResolver:
      | ToResponseUnion<GetPetByIdResponses>
      | HttpResponseResolver<StringifyPathParams<NonNullable<GetPetByIdData['path']>>, never>,
    options?: RequestHandlerOptions,
  ) => HttpHandler;
  getUserByName: (
    responseOrResolver:
      | ToResponseUnion<GetUserByNameResponses>
      | HttpResponseResolver<StringifyPathParams<NonNullable<GetUserByNameData['path']>>, never>,
    options?: RequestHandlerOptions,
  ) => HttpHandler;
  loginUser: (
    responseOrResolver: ToResponseUnion<LoginUserResponses> | HttpResponseResolver,
    options?: RequestHandlerOptions,
  ) => HttpHandler;
  logoutUser: (
    responseOrResolver?: ToResponseUnion<LogoutUserResponses> | HttpResponseResolver,
    options?: RequestHandlerOptions,
  ) => HttpHandler;
  placeOrder: (
    responseOrResolver:
      | ToResponseUnion<PlaceOrderResponses>
      | HttpResponseResolver<never, PlaceOrderData['body']>,
    options?: RequestHandlerOptions,
  ) => HttpHandler;
  updatePet: (
    responseOrResolver:
      | ToResponseUnion<UpdatePetResponses>
      | HttpResponseResolver<never, UpdatePetData['body']>,
    options?: RequestHandlerOptions,
  ) => HttpHandler;
  updatePetWithForm: (
    responseOrResolver:
      | ToResponseUnion<UpdatePetWithFormResponses>
      | HttpResponseResolver<
          StringifyPathParams<NonNullable<UpdatePetWithFormData['path']>>,
          never
        >,
    options?: RequestHandlerOptions,
  ) => HttpHandler;
  updateUser: (
    responseOrResolver?:
      | ToResponseUnion<UpdateUserResponses>
      | HttpResponseResolver<
          StringifyPathParams<NonNullable<UpdateUserData['path']>>,
          UpdateUserData['body']
        >,
    options?: RequestHandlerOptions,
  ) => HttpHandler;
  uploadFile: (
    responseOrResolver:
      | ToResponseUnion<UploadFileResponses>
      | HttpResponseResolver<
          StringifyPathParams<NonNullable<UploadFileData['path']>>,
          UploadFileData['body']
        >,
    options?: RequestHandlerOptions,
  ) => HttpHandler;
};

export type MswHandlerFactory = {
  of: SingleHandlerFactories;
};

export const createMswHandlerFactory = (config?: { baseUrl?: string }): MswHandlerFactory => {
  const baseUrl = config?.baseUrl ?? 'https://petstore3.swagger.io/api/v3';
  const of: SingleHandlerFactories = {
    addPet: (res, options) =>
      http.post(
        toMswPath('/pet', baseUrl),
        typeof res === 'object' && res.status
          ? () => HttpResponse.json(res.result ?? null, { status: res.status })
          : typeof res === 'function'
            ? res
            : resolveToNull,
        options,
      ),
    createUser: (res, options) =>
      http.post(
        toMswPath('/user', baseUrl),
        typeof res === 'object' && res.status
          ? () => HttpResponse.json(res.result ?? null, { status: res.status })
          : typeof res === 'function'
            ? res
            : resolveToNull,
        options,
      ),
    createUsersWithListInput: (res, options) =>
      http.post(
        toMswPath('/user/createWithList', baseUrl),
        typeof res === 'object' && res.status
          ? () => HttpResponse.json(res.result ?? null, { status: res.status })
          : typeof res === 'function'
            ? res
            : resolveToNull,
        options,
      ),
    deleteOrder: (res, options) =>
      http.delete(
        toMswPath('/store/order/{orderId}', baseUrl),
        typeof res === 'object' && res.status
          ? () => new HttpResponse(res.result ?? null, { status: res.status })
          : typeof res === 'function'
            ? res
            : resolveToNull,
        options,
      ),
    deletePet: (res, options) =>
      http.delete(
        toMswPath('/pet/{petId}', baseUrl),
        typeof res === 'object' && res.status
          ? () => new HttpResponse(res.result ?? null, { status: res.status })
          : typeof res === 'function'
            ? res
            : resolveToNull,
        options,
      ),
    deleteUser: (res, options) =>
      http.delete(
        toMswPath('/user/{username}', baseUrl),
        typeof res === 'object' && res.status
          ? () => new HttpResponse(res.result ?? null, { status: res.status })
          : typeof res === 'function'
            ? res
            : resolveToNull,
        options,
      ),
    findPetsByStatus: (res, options) =>
      http.get(
        toMswPath('/pet/findByStatus', baseUrl),
        typeof res === 'object' && res.status
          ? () => HttpResponse.json(res.result ?? null, { status: res.status })
          : typeof res === 'function'
            ? res
            : resolveToNull,
        options,
      ),
    findPetsByTags: (res, options) =>
      http.get(
        toMswPath('/pet/findByTags', baseUrl),
        typeof res === 'object' && res.status
          ? () => HttpResponse.json(res.result ?? null, { status: res.status })
          : typeof res === 'function'
            ? res
            : resolveToNull,
        options,
      ),
    getInventory: (res, options) =>
      http.get(
        toMswPath('/store/inventory', baseUrl),
        typeof res === 'object' && res.status
          ? () => HttpResponse.json(res.result ?? null, { status: res.status })
          : typeof res === 'function'
            ? res
            : resolveToNull,
        options,
      ),
    getOrderById: (res, options) =>
      http.get(
        toMswPath('/store/order/{orderId}', baseUrl),
        typeof res === 'object' && res.status
          ? () => HttpResponse.json(res.result ?? null, { status: res.status })
          : typeof res === 'function'
            ? res
            : resolveToNull,
        options,
      ),
    getPetById: (res, options) =>
      http.get(
        toMswPath('/pet/{petId}', baseUrl),
        typeof res === 'object' && res.status
          ? () => HttpResponse.json(res.result ?? null, { status: res.status })
          : typeof res === 'function'
            ? res
            : resolveToNull,
        options,
      ),
    getUserByName: (res, options) =>
      http.get(
        toMswPath('/user/{username}', baseUrl),
        typeof res === 'object' && res.status
          ? () => HttpResponse.json(res.result ?? null, { status: res.status })
          : typeof res === 'function'
            ? res
            : resolveToNull,
        options,
      ),
    loginUser: (res, options) =>
      http.get(
        toMswPath('/user/login', baseUrl),
        typeof res === 'object' && res.status
          ? () => HttpResponse.json(res.result ?? null, { status: res.status })
          : typeof res === 'function'
            ? res
            : resolveToNull,
        options,
      ),
    logoutUser: (res, options) =>
      http.get(
        toMswPath('/user/logout', baseUrl),
        typeof res === 'object' && res.status
          ? () => new HttpResponse(res.result ?? null, { status: res.status })
          : typeof res === 'function'
            ? res
            : resolveToNull,
        options,
      ),
    placeOrder: (res, options) =>
      http.post(
        toMswPath('/store/order', baseUrl),
        typeof res === 'object' && res.status
          ? () => HttpResponse.json(res.result ?? null, { status: res.status })
          : typeof res === 'function'
            ? res
            : resolveToNull,
        options,
      ),
    updatePet: (res, options) =>
      http.put(
        toMswPath('/pet', baseUrl),
        typeof res === 'object' && res.status
          ? () => HttpResponse.json(res.result ?? null, { status: res.status })
          : typeof res === 'function'
            ? res
            : resolveToNull,
        options,
      ),
    updatePetWithForm: (res, options) =>
      http.post(
        toMswPath('/pet/{petId}', baseUrl),
        typeof res === 'object' && res.status
          ? () => HttpResponse.json(res.result ?? null, { status: res.status })
          : typeof res === 'function'
            ? res
            : resolveToNull,
        options,
      ),
    updateUser: (res, options) =>
      http.put(
        toMswPath('/user/{username}', baseUrl),
        typeof res === 'object' && res.status
          ? () => new HttpResponse(res.result ?? null, { status: res.status })
          : typeof res === 'function'
            ? res
            : resolveToNull,
        options,
      ),
    uploadFile: (res, options) =>
      http.post(
        toMswPath('/pet/{petId}/uploadImage', baseUrl),
        typeof res === 'object' && res.status
          ? () => HttpResponse.json(res.result ?? null, { status: res.status })
          : typeof res === 'function'
            ? res
            : resolveToNull,
        options,
      ),
  };
  return { of };
};
