openapi: 3.1.0
info:
  title: Faker basic test
  version: '1'
paths: {}
components:
  schemas:
    Foo:
      properties:
        name:
          type: string
        age:
          type: integer
        active:
          type: boolean
      required:
        - name
        - age
      type: object
    Bar:
      type: string
      enum:
        - baz
        - qux
