// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Foo = {
    name: string;
    age: number;
    active?: boolean;
};

export type Bar = 'baz' | 'qux';
