// This file is auto-generated by @hey-api/openapi-ts

import { faker, type Faker } from '@faker-js/faker';

import type { Active, Anything, Nothing, NumericEnum, Pet, PetList, PetOrTag, Price, Quantity, StatusWithNull, StringOrNumber, Tag, Tags } from '../types.gen';

export const fakePrice = (options?: {
    faker?: Faker;
}): Price => (options?.faker ?? faker).number.float();

export const fakeQuantity = (options?: {
    faker?: Faker;
}): Quantity => (options?.faker ?? faker).number.int();

export const fakeActive = (options?: {
    faker?: Faker;
}): Active => (options?.faker ?? faker).datatype.boolean();

export const fakeNothing = (): Nothing => null;

export const fakeAnything = (): Anything => undefined;

export const fakeStatusWithNull = (options?: {
    faker?: Faker;
}): StatusWithNull => (options?.faker ?? faker).helpers.arrayElement([
    'active',
    'inactive',
    null
]);

export const fakeNumericEnum = (options?: {
    faker?: Faker;
}): NumericEnum => (options?.faker ?? faker).helpers.arrayElement([
    1,
    2,
    3
]);

export const fakeTags = (options?: {
    faker?: Faker;
}): Tags => (options?.faker ?? faker).helpers.multiple(() => (options?.faker ?? faker).string.sample());

export const fakeTag = (options?: {
    faker?: Faker;
}): Tag => ({
    id: (options?.faker ?? faker).number.int(),
    label: (options?.faker ?? faker).string.sample()
});

export const fakePet = (options?: {
    faker?: Faker;
}): Pet => ({
    name: (options?.faker ?? faker).string.sample(),
    tag: fakeTag(options)
});

export const fakePetOrTag = (options?: {
    faker?: Faker;
}): PetOrTag => fakePet(options);

export const fakeStringOrNumber = (options?: {
    faker?: Faker;
}): StringOrNumber => (options?.faker ?? faker).string.sample();

export const fakePetList = (options?: {
    faker?: Faker;
}): PetList => (options?.faker ?? faker).helpers.multiple(() => fakePet(options));
