// This file is auto-generated by @hey-api/openapi-ts

import { faker, type Faker } from '@faker-js/faker';

import type { Active, Anything, Nothing, NumericEnum, Pet, PetList, PetOrTag, Price, Quantity, StatusWithNull, StringOrNumber, Tag, Tags } from '../types.gen';

export type Options = {
    faker?: Faker;
    /**
     * Whether to include optional properties.
     * Provide a number between 0 and 1 to randomly include based on that probability.
     * @default true
     */
    includeOptional?: boolean | number;
    /**
     * Whether to use schema default values instead of generating fake data.
     * Provide a number between 0 and 1 to randomly use defaults based on that probability.
     * @default false
     */
    useDefault?: boolean | number;
};

const resolveCondition = (condition: boolean | number, faker: Faker): boolean => condition === true || typeof condition === 'number' && faker.datatype.boolean({ probability: condition });

const ensureFaker = (options?: Options): Faker => options?.faker ?? faker;

export const fakePrice = (options?: Options): Price => ensureFaker(options).number.float();

export const fakeQuantity = (options?: Options): Quantity => ensureFaker(options).number.int();

export const fakeActive = (options?: Options): Active => ensureFaker(options).datatype.boolean();

export const fakeNothing = (): Nothing => null;

export const fakeAnything = (): Anything => undefined;

export const fakeStatusWithNull = (options?: Options): StatusWithNull => ensureFaker(options).helpers.arrayElement([
    'active',
    'inactive',
    null
]);

export const fakeNumericEnum = (options?: Options): NumericEnum => ensureFaker(options).helpers.arrayElement([
    1,
    2,
    3
]);

export const fakeTags = (options?: Options): Tags => ensureFaker(options).helpers.multiple(() => ensureFaker(options).string.sample());

export const fakeTag = (options?: Options): Tag => ({
    id: ensureFaker(options).number.int(),
    label: ensureFaker(options).string.sample()
});

export const fakePet = (options?: Options): Pet => ({
    name: ensureFaker(options).string.sample(),
    ...!resolveCondition(options?.includeOptional ?? true, ensureFaker(options)) ? {} : { tag: fakeTag(options) }
});

export const fakePetOrTag = (options?: Options): PetOrTag => fakePet(options);

export const fakeStringOrNumber = (options?: Options): StringOrNumber => ensureFaker(options).string.sample();

export const fakePetList = (options?: Options): PetList => ensureFaker(options).helpers.multiple(() => fakePet(options));
