// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Email = string;

export type DateTime = string;

export type DateOnly = string;

export type UniqueId = string;

export type Website = string;

export type IPv4Address = string;

export type IPv6Address = string;

export type ZipCode = string;

export type ShortName = string;

export type MinOnlyString = string;

export type MaxOnlyString = string;

export type EmailWithLength = string;

export type BoundedInt = number;

export type BoundedFloat = number;

export type ExclusiveInt = number;

export type MinOnlyNumber = number;

export type MaxOnlyInt = number;

export type TagList = Array<string>;

export type MinOnlyArray = Array<number>;

export type MaxOnlyArray = Array<string>;

export type UnconstrainedArray = Array<string>;

export type DefaultString = string;

export type DefaultInt = number;

export type DefaultBool = boolean;

export type DefaultOverridesConstraints = number;

export type ExclusiveFloat = number;

export type ExclusiveFloatNarrow = number;

export type NullableString = string | null;

export type NullableInt = number | null;

export type ObjectWithDefaultProp = {
    name: string;
    status?: string;
};

export type UserProfile = {
    id: number;
    name: string;
    bio?: string;
    age?: number;
};

export type Address = {
    street: string;
    zip: ZipCode;
};

export type Person = {
    name: ShortName;
    email: Email;
    address?: Address;
};

export type PersonList = Array<Person>;

export type Team = {
    lead: Person;
    config: ObjectWithDefaultProp;
};
