// This file is auto-generated by @hey-api/openapi-ts

export type { ClientOptions, CreateJobData, CreateJobError, CreateJobErrors, CreateJobResponse, CreateJobResponses, CreatePetData, CreatePetResponse, CreatePetResponses, DeletePetData, DeletePetError, DeletePetErrors, DeletePetResponse, DeletePetResponses, Error, GetPetData, GetPetError, GetPetErrors, GetPetResponse, GetPetResponses, HealthCheckData, HealthCheckResponse, HealthCheckResponses, ListPetsData, ListPetsResponse, ListPetsResponses, Pet } from './types.gen';
