// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Pet = {
    id: string;
    name: string;
    age?: number;
};

export type Error = {
    code: number;
    message: string;
};

export type ListPetsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/pets';
};

export type ListPetsResponses = {
    /**
     * A list of pets
     */
    200: Array<Pet>;
};

export type ListPetsResponse = ListPetsResponses[keyof ListPetsResponses];

export type CreatePetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/pets';
};

export type CreatePetResponses = {
    /**
     * Pet created
     */
    201: Pet;
    /**
     * No content
     */
    204: void;
};

export type CreatePetResponse = CreatePetResponses[keyof CreatePetResponses];

export type DeletePetData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/pets/{id}';
};

export type DeletePetErrors = {
    /**
     * Not found
     */
    404: Error;
};

export type DeletePetError = DeletePetErrors[keyof DeletePetErrors];

export type DeletePetResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeletePetResponse = DeletePetResponses[keyof DeletePetResponses];

export type GetPetData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/pets/{id}';
};

export type GetPetErrors = {
    /**
     * Not found
     */
    404: Error;
};

export type GetPetError = GetPetErrors[keyof GetPetErrors];

export type GetPetResponses = {
    /**
     * A pet
     */
    200: Pet;
};

export type GetPetResponse = GetPetResponses[keyof GetPetResponses];

export type CreateJobData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/jobs';
};

export type CreateJobErrors = {
    /**
     * Client error
     */
    '4XX': Error;
};

export type CreateJobError = CreateJobErrors[keyof CreateJobErrors];

export type CreateJobResponses = {
    /**
     * Job accepted
     */
    '2XX': Pet;
};

export type CreateJobResponse = CreateJobResponses[keyof CreateJobResponses];

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckResponses = {
    /**
     * OK
     */
    200: string;
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];
