// This file is auto-generated by @hey-api/openapi-ts

import { http, type HttpHandler, HttpResponse, type HttpResponseResolver, type RequestHandlerOptions } from 'msw';

import type { CallWithDuplicateResponsesResponses, CallWithNoContentResponseResponses, CallWithParametersData, CallWithResponseAndNoContentResponseResponses, CallWithResponsesResponses, CallWithResultFromHeaderResponses, CallWithWeirdParameterNamesData, ComplexTypesResponses, DummyAResponses, DummyBResponses, NonAsciiæøåÆøÅöôêÊ字符串Responses, PostApiVbyApiVersionBodyData, PostApiVbyApiVersionBodyResponses, TestErrorCodeResponses, TypesData, TypesResponses } from './types.gen';

const toMswPath = (path: string, baseUrl: string) => `${baseUrl}${path.replace(/\{([^}]+)\}/g, ':$1')}`;

const resolveToNull = () => new HttpResponse(null);

type ToResponseUnion<T> = {
    [K in Extract<keyof T, number>]: {
        status: K;
        result: T[K];
    };
}[Extract<keyof T, number>];

type StringifyPathParams<T> = {
    [K in keyof T]-?: string | ReadonlyArray<string>;
};

export type SingleHandlerFactories = {
    serviceWithEmptyTag: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    patchApiVbyApiVersionNoTag: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    fooWow: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    deleteCallWithoutParametersAndResponse: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    getCallWithoutParametersAndResponse: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    headCallWithoutParametersAndResponse: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    optionsCallWithoutParametersAndResponse: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    patchCallWithoutParametersAndResponse: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    postCallWithoutParametersAndResponse: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    putCallWithoutParametersAndResponse: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    callWithDescriptions: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    callWithParameters: (responseOrResolver?: HttpResponseResolver<StringifyPathParams<NonNullable<CallWithParametersData['path']>>, never>, options?: RequestHandlerOptions) => HttpHandler;
    callWithWeirdParameterNames: (responseOrResolver?: HttpResponseResolver<StringifyPathParams<NonNullable<CallWithWeirdParameterNamesData['path']>>, CallWithWeirdParameterNamesData['body']>, options?: RequestHandlerOptions) => HttpHandler;
    callWithDefaultParameters: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    callWithDefaultOptionalParameters: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    callToTestOrderOfParams: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    duplicateName: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    duplicateName2: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    duplicateName3: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    duplicateName4: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    callWithNoContentResponse: (responseOrResolver?: ToResponseUnion<CallWithNoContentResponseResponses> | HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    callWithResponseAndNoContentResponse: (responseOrResolver: ToResponseUnion<CallWithResponseAndNoContentResponseResponses> | HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    dummyA: (responseOrResolver?: ToResponseUnion<DummyAResponses> | HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    dummyB: (responseOrResolver?: ToResponseUnion<DummyBResponses> | HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    callWithResponse: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    callWithDuplicateResponses: (responseOrResolver: ToResponseUnion<CallWithDuplicateResponsesResponses> | HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    callWithResponses: (responseOrResolver: ToResponseUnion<CallWithResponsesResponses> | HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    collectionFormat: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    types: (responseOrResolver: ToResponseUnion<TypesResponses> | HttpResponseResolver<StringifyPathParams<NonNullable<TypesData['path']>>, never>, options?: RequestHandlerOptions) => HttpHandler;
    complexTypes: (responseOrResolver: ToResponseUnion<ComplexTypesResponses> | HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    callWithResultFromHeader: (responseOrResolver?: ToResponseUnion<CallWithResultFromHeaderResponses> | HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    testErrorCode: (responseOrResolver?: ToResponseUnion<TestErrorCodeResponses> | HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    nonAsciiæøåÆøÅöôêÊ字符串: (responseOrResolver: ToResponseUnion<NonAsciiæøåÆøÅöôêÊ字符串Responses> | HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    postApiVbyApiVersionBody: (responseOrResolver: ToResponseUnion<PostApiVbyApiVersionBodyResponses> | HttpResponseResolver<never, PostApiVbyApiVersionBodyData['body']>, options?: RequestHandlerOptions) => HttpHandler;
};

export type MswHandlerFactory = {
    of: SingleHandlerFactories;
};

export const createMswHandlerFactory = (config?: {
    baseUrl?: string;
}): MswHandlerFactory => {
    const baseUrl = config?.baseUrl ?? 'http://localhost:3000/base';
    const of: SingleHandlerFactories = {
        serviceWithEmptyTag: (res, options) => http.get(toMswPath('/api/v{api-version}/no+tag', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        patchApiVbyApiVersionNoTag: (res, options) => http.patch(toMswPath('/api/v{api-version}/no+tag', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        fooWow: (res, options) => http.put(toMswPath('/api/v{api-version}/no+tag', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        deleteCallWithoutParametersAndResponse: (res, options) => http.delete(toMswPath('/api/v{api-version}/simple', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        getCallWithoutParametersAndResponse: (res, options) => http.get(toMswPath('/api/v{api-version}/simple', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        headCallWithoutParametersAndResponse: (res, options) => http.head(toMswPath('/api/v{api-version}/simple', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        optionsCallWithoutParametersAndResponse: (res, options) => http.options(toMswPath('/api/v{api-version}/simple', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        patchCallWithoutParametersAndResponse: (res, options) => http.patch(toMswPath('/api/v{api-version}/simple', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        postCallWithoutParametersAndResponse: (res, options) => http.post(toMswPath('/api/v{api-version}/simple', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        putCallWithoutParametersAndResponse: (res, options) => http.put(toMswPath('/api/v{api-version}/simple', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        callWithDescriptions: (res, options) => http.post(toMswPath('/api/v{api-version}/descriptions/', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        callWithParameters: (res, options) => http.post(toMswPath('/api/v{api-version}/parameters/{parameterPath}', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        callWithWeirdParameterNames: (res, options) => http.post(toMswPath('/api/v{api-version}/parameters/{parameter.path.1}/{parameter-path-2}/{PARAMETER-PATH-3}', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        callWithDefaultParameters: (res, options) => http.get(toMswPath('/api/v{api-version}/defaults', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        callWithDefaultOptionalParameters: (res, options) => http.post(toMswPath('/api/v{api-version}/defaults', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        callToTestOrderOfParams: (res, options) => http.put(toMswPath('/api/v{api-version}/defaults', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        duplicateName: (res, options) => http.delete(toMswPath('/api/v{api-version}/duplicate', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        duplicateName2: (res, options) => http.get(toMswPath('/api/v{api-version}/duplicate', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        duplicateName3: (res, options) => http.post(toMswPath('/api/v{api-version}/duplicate', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        duplicateName4: (res, options) => http.put(toMswPath('/api/v{api-version}/duplicate', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        callWithNoContentResponse: (res, options) => http.get(toMswPath('/api/v{api-version}/no-content', baseUrl), typeof res === 'object' && res.status ? () => new HttpResponse(res.result ?? null, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options),
        callWithResponseAndNoContentResponse: (res, options) => http.get(toMswPath('/api/v{api-version}/multiple-tags/response-and-no-content', baseUrl), typeof res === 'object' && res.status ? () => HttpResponse.json(res.result ?? null, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options),
        dummyA: (res, options) => http.get(toMswPath('/api/v{api-version}/multiple-tags/a', baseUrl), typeof res === 'object' && res.status ? () => new HttpResponse(res.result ?? null, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options),
        dummyB: (res, options) => http.get(toMswPath('/api/v{api-version}/multiple-tags/b', baseUrl), typeof res === 'object' && res.status ? () => new HttpResponse(res.result ?? null, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options),
        callWithResponse: (res, options) => http.get(toMswPath('/api/v{api-version}/response', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        callWithDuplicateResponses: (res, options) => http.post(toMswPath('/api/v{api-version}/response', baseUrl), typeof res === 'object' && res.status ? () => HttpResponse.json(res.result ?? null, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options),
        callWithResponses: (res, options) => http.put(toMswPath('/api/v{api-version}/response', baseUrl), typeof res === 'object' && res.status ? () => HttpResponse.json(res.result ?? null, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options),
        collectionFormat: (res, options) => http.get(toMswPath('/api/v{api-version}/collectionFormat', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        types: (res, options) => http.get(toMswPath('/api/v{api-version}/types', baseUrl), typeof res === 'object' && res.status ? () => HttpResponse.json(res.result ?? null, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options),
        complexTypes: (res, options) => http.get(toMswPath('/api/v{api-version}/complex', baseUrl), typeof res === 'object' && res.status ? () => HttpResponse.json(res.result ?? null, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options),
        callWithResultFromHeader: (res, options) => http.post(toMswPath('/api/v{api-version}/header', baseUrl), typeof res === 'object' && res.status ? () => new HttpResponse(res.result ?? null, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options),
        testErrorCode: (res, options) => http.post(toMswPath('/api/v{api-version}/error', baseUrl), typeof res === 'object' && res.status ? () => new HttpResponse(res.result ?? null, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options),
        nonAsciiæøåÆøÅöôêÊ字符串: (res, options) => http.post(toMswPath('/api/v{api-version}/non-ascii-æøåÆØÅöôêÊ字符串', baseUrl), typeof res === 'object' && res.status ? () => HttpResponse.json(res.result ?? null, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options),
        postApiVbyApiVersionBody: (res, options) => http.post(toMswPath('/api/v{api-version}/body', baseUrl), typeof res === 'object' && res.status ? () => HttpResponse.json(res.result ?? null, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options)
    };
    return { of };
};
