// This file is auto-generated by @hey-api/openapi-ts

import { faker, type Faker } from '@faker-js/faker';

export const fakeFoo = (options?: {
    faker?: Faker;
}) => ({
    name: (options?.faker ?? faker).string.sample(),
    age: (options?.faker ?? faker).number.int(),
    active: (options?.faker ?? faker).datatype.boolean()
});

export const fakeBar = (options?: {
    faker?: Faker;
}) => (options?.faker ?? faker).helpers.arrayElement(['baz', 'qux']);
