// This file is auto-generated by @hey-api/openapi-ts

import type { Faker } from '@faker-js/faker';
import { faker } from '@faker-js/faker/locale/de';

export type Options = {
    faker?: Faker;
    /**
     * Whether to include optional properties.
     * Provide a number between 0 and 1 to randomly include based on that probability.
     * @default true
     */
    includeOptional?: boolean | number;
    /**
     * Whether to use schema default values instead of generating fake data.
     * Provide a number between 0 and 1 to randomly use defaults based on that probability.
     * @default false
     */
    useDefault?: boolean | number;
};

const resolveCondition = (condition: boolean | number, faker: Faker): boolean => condition === true || typeof condition === 'number' && faker.datatype.boolean({ probability: condition });

const ensureFaker = (options?: Options): Faker => options?.faker ?? faker;

export const fakePrice = (options?: Options) => ensureFaker(options).number.float();

export const fakeQuantity = (options?: Options) => ensureFaker(options).number.int();

export const fakeActive = (options?: Options) => ensureFaker(options).datatype.boolean();

export const fakeNumericEnum = (options?: Options) => ensureFaker(options).helpers.arrayElement([
    1,
    2,
    3
]);

export const fakeEmail = (options?: Options) => ensureFaker(options).internet.email();

export const fakeDateTime = (options?: Options) => ensureFaker(options).date.recent().toISOString();

export const fakeDateOnly = (options?: Options) => ensureFaker(options).date.recent().toISOString().slice(0, 10);

export const fakeUniqueId = (options?: Options) => ensureFaker(options).string.uuid();

export const fakeWebsite = (options?: Options) => ensureFaker(options).internet.url();

export const fakeIPv4Address = (options?: Options) => ensureFaker(options).internet.ipv4();

export const fakeIPv6Address = (options?: Options) => ensureFaker(options).internet.ipv6();

export const fakeZipCode = (options?: Options) => ensureFaker(options).helpers.fromRegExp('^\\d{5}(-\\d{4})?$');

export const fakeShortName = (options?: Options) => ensureFaker(options).string.alpha({ length: { min: 2, max: 50 } });

export const fakeMinOnlyString = (options?: Options) => ensureFaker(options).string.alpha({ length: { min: 10, max: 1000 } });

export const fakeMaxOnlyString = (options?: Options) => ensureFaker(options).string.alpha({ length: { min: 0, max: 5 } });

export const fakeEmailWithLength = (options?: Options) => ensureFaker(options).internet.email();

export const fakeBoundedInt = (options?: Options) => ensureFaker(options).number.int({ min: 1, max: 100 });

export const fakeBoundedFloat = (options?: Options) => ensureFaker(options).number.float({ min: 0, max: 1 });

export const fakeExclusiveInt = (options?: Options) => ensureFaker(options).number.int({ min: 1, max: 9 });

export const fakeMinOnlyNumber = (options?: Options) => ensureFaker(options).number.float({ min: 0 });

export const fakeMaxOnlyInt = (options?: Options) => ensureFaker(options).number.int({ max: 999 });

export const fakeExclusiveFloat = (options?: Options) => ensureFaker(options).number.float({ min: 0, max: 1 });

export const fakeExclusiveFloatNarrow = (options?: Options) => ensureFaker(options).number.float({ min: 10.1, max: 10.2 });

export const fakeTags = (options?: Options) => ensureFaker(options).helpers.multiple(() => ensureFaker(options).string.sample());

export const fakeTagList = (options?: Options) => ensureFaker(options).helpers.multiple(() => ensureFaker(options).string.sample(), { count: { min: 1, max: 10 } });

export const fakeMinOnlyArray = (options?: Options) => ensureFaker(options).helpers.multiple(() => ensureFaker(options).number.int(), { count: { min: 3, max: 1000 } });

export const fakeMaxOnlyArray = (options?: Options) => ensureFaker(options).helpers.multiple(() => ensureFaker(options).string.sample(), { count: { min: 0, max: 5 } });

export const fakeDefaultString = (options?: Options) => resolveCondition(options?.useDefault ?? false, ensureFaker(options)) ? 'unknown' : ensureFaker(options).string.sample();

export const fakeDefaultInt = (options?: Options) => resolveCondition(options?.useDefault ?? false, ensureFaker(options)) ? 0 : ensureFaker(options).number.int();

export const fakeDefaultBool = (options?: Options) => resolveCondition(options?.useDefault ?? false, ensureFaker(options)) ? true : ensureFaker(options).datatype.boolean();

export const fakeDefaultOverridesConstraints = (options?: Options) => resolveCondition(options?.useDefault ?? false, ensureFaker(options)) ? 42 : ensureFaker(options).number.int({ min: 1, max: 100 });

export const fakeNullableString = (options?: Options) => ensureFaker(options).datatype.boolean() ? ensureFaker(options).string.sample() : null;

export const fakeNullableInt = (options?: Options) => ensureFaker(options).datatype.boolean() ? ensureFaker(options).number.int() : null;

export const fakeObjectWithDefaultProp = (options?: Options) => ({
    name: ensureFaker(options).string.sample(),
    ...!resolveCondition(options?.includeOptional ?? true, ensureFaker(options)) ? {} : { status: resolveCondition(options?.useDefault ?? false, ensureFaker(options)) ? 'active' : ensureFaker(options).string.sample() }
});

export const fakeUserProfile = (options?: Options) => ({
    id: ensureFaker(options).number.int(),
    name: ensureFaker(options).string.sample(),
    ...!resolveCondition(options?.includeOptional ?? true, ensureFaker(options)) ? {} : { bio: ensureFaker(options).lorem.sentence() },
    ...!resolveCondition(options?.includeOptional ?? true, ensureFaker(options)) ? {} : { age: ensureFaker(options).number.int({ min: 1, max: 120 }) }
});

export const fakeTag = (options?: Options) => ({
    id: ensureFaker(options).number.int(),
    label: ensureFaker(options).string.sample()
});

export const fakePet = (options?: Options) => ({
    id: ensureFaker(options).string.uuid(),
    name: ensureFaker(options).string.sample(),
    ...!resolveCondition(options?.includeOptional ?? true, ensureFaker(options)) ? {} : { age: ensureFaker(options).number.int({ min: 1, max: 120 }) },
    ...!resolveCondition(options?.includeOptional ?? true, ensureFaker(options)) ? {} : { tag: fakeTag(options) }
});

export const fakeError = (options?: Options) => ({
    code: ensureFaker(options).number.int(),
    message: ensureFaker(options).string.sample()
});

export const fakeAddress = (options?: Options) => ({
    street: ensureFaker(options).location.streetAddress(),
    zip: fakeZipCode(options)
});

export const fakePerson = (options?: Options) => ({
    name: fakeShortName(options),
    email: fakeEmail(options),
    ...!resolveCondition(options?.includeOptional ?? true, ensureFaker(options)) ? {} : { address: fakeAddress(options) }
});

export const fakePersonList = (options?: Options) => ensureFaker(options).helpers.multiple(() => fakePerson(options), { count: { min: 1, max: 20 } });

export const fakePetList = (options?: Options) => ensureFaker(options).helpers.multiple(() => fakePet(options));

export const fakeTeam = (options?: Options) => ({
    lead: fakePerson(options),
    config: fakeObjectWithDefaultProp(options)
});

export const fakePetWithOwner = (options?: Options) => ({
    ...fakePet(options),
    ...{
        owner: ensureFaker(options).string.sample()
    }
});

export const fakePersonProfile = (options?: Options) => ({
    firstName: ensureFaker(options).person.firstName(),
    last_name: ensureFaker(options).person.lastName(),
    email: ensureFaker(options).internet.email(),
    phone: ensureFaker(options).phone.number(),
    age: ensureFaker(options).number.int({ min: 1, max: 120 }),
    city: ensureFaker(options).location.city(),
    postalCode: ensureFaker(options).location.zipCode(),
    bio: ensureFaker(options).lorem.sentence(),
    website: ensureFaker(options).internet.url(),
    zipCode: ensureFaker(options).helpers.fromRegExp('^\\d{5}$'),
    username: ensureFaker(options).internet.username(),
    someRandomField: ensureFaker(options).string.sample()
});

export const fakePersonWithConstraints = (options?: Options) => ({
    age: ensureFaker(options).number.int({ min: 18, max: 120 }),
    ...!resolveCondition(options?.includeOptional ?? true, ensureFaker(options)) ? {} : { seniorAge: ensureFaker(options).number.int({ min: 65, max: 100 }) }
});

export const fakeUser = (options?: Options) => ({
    name: ensureFaker(options).person.fullName(),
    email: ensureFaker(options).internet.email()
});

export const fakeCompany = (options?: Options) => ({
    name: ensureFaker(options).company.name()
});

export const fakeConfig = (options?: Options) => ({
    name: ensureFaker(options).string.sample()
});

export const fakeDocument = (options?: Options) => ({
    id: ensureFaker(options).string.uuid(),
    _id: ensureFaker(options).string.uuid(),
    numericId: ensureFaker(options).number.int()
});

export const fakeListPetsResponse = (options?: Options) => ensureFaker(options).helpers.multiple(() => fakePet(options));

export const fakeCreatePetResponse201 = (options?: Options) => fakePet(options);

export const fakeCreatePetResponse204 = () => undefined;

export const fakeDeletePetResponse204 = () => undefined;

export const fakeDeletePetResponse404 = (options?: Options) => fakeError(options);

export const fakeGetPetResponse200 = (options?: Options) => fakePet(options);

export const fakeGetPetResponse404 = (options?: Options) => fakeError(options);

export const fakeHealthCheckResponse = (options?: Options) => ensureFaker(options).string.sample();
