// This file is auto-generated by @hey-api/openapi-ts

import { faker, type Faker } from '@faker-js/faker';

import type { Active, Address, BoundedFloat, BoundedInt, Company, Config, CreatePetResponses, DateOnly, DateTime, DefaultBool, DefaultInt, DefaultOverridesConstraints, DefaultString, DeletePetErrors, DeletePetResponses, Document, Email, EmailWithLength, Error, ExclusiveFloat, ExclusiveFloatNarrow, ExclusiveInt, GetPetErrors, GetPetResponses, HealthCheckResponse, IPv4Address, IPv6Address, ListPetsResponse, MaxOnlyArray, MaxOnlyInt, MaxOnlyString, MinOnlyArray, MinOnlyNumber, MinOnlyString, NullableInt, NullableString, NumericEnum, ObjectWithDefaultProp, Person, PersonList, PersonProfile, PersonWithConstraints, Pet, PetList, PetWithOwner, Price, Quantity, ShortName, Tag, TagList, Tags, Team, UniqueId, User, UserProfile, Website, ZipCode } from '../types.gen';

export type Options = {
    faker?: Faker;
    /**
     * Whether to include optional properties.
     * Provide a number between 0 and 1 to randomly include based on that probability.
     * @default true
     */
    includeOptional?: boolean | number;
    /**
     * Whether to use schema default values instead of generating fake data.
     * Provide a number between 0 and 1 to randomly use defaults based on that probability.
     * @default false
     */
    useDefault?: boolean | number;
};

const resolveCondition = (condition: boolean | number, faker: Faker): boolean => condition === true || typeof condition === 'number' && faker.datatype.boolean({ probability: condition });

const ensureFaker = (options?: Options): Faker => options?.faker ?? faker;

export const fakePrice = (options?: Options): Price => ensureFaker(options).number.float();

export const fakeQuantity = (options?: Options): Quantity => ensureFaker(options).number.int();

export const fakeActive = (options?: Options): Active => ensureFaker(options).datatype.boolean();

export const fakeNumericEnum = (options?: Options): NumericEnum => ensureFaker(options).helpers.arrayElement([
    1,
    2,
    3
]);

export const fakeEmail = (options?: Options): Email => ensureFaker(options).internet.email();

export const fakeDateTime = (options?: Options): DateTime => ensureFaker(options).date.recent().toISOString();

export const fakeDateOnly = (options?: Options): DateOnly => ensureFaker(options).date.recent().toISOString().slice(0, 10);

export const fakeUniqueId = (options?: Options): UniqueId => ensureFaker(options).string.uuid();

export const fakeWebsite = (options?: Options): Website => ensureFaker(options).internet.url();

export const fakeIPv4Address = (options?: Options): IPv4Address => ensureFaker(options).internet.ipv4();

export const fakeIPv6Address = (options?: Options): IPv6Address => ensureFaker(options).internet.ipv6();

export const fakeZipCode = (options?: Options): ZipCode => ensureFaker(options).helpers.fromRegExp('^\\d{5}(-\\d{4})?$');

export const fakeShortName = (options?: Options): ShortName => ensureFaker(options).string.alpha({ length: { min: 2, max: 50 } });

export const fakeMinOnlyString = (options?: Options): MinOnlyString => ensureFaker(options).string.alpha({ length: { min: 10, max: 1000 } });

export const fakeMaxOnlyString = (options?: Options): MaxOnlyString => ensureFaker(options).string.alpha({ length: { min: 0, max: 5 } });

export const fakeEmailWithLength = (options?: Options): EmailWithLength => ensureFaker(options).internet.email();

export const fakeBoundedInt = (options?: Options): BoundedInt => ensureFaker(options).number.int({ min: 1, max: 100 });

export const fakeBoundedFloat = (options?: Options): BoundedFloat => ensureFaker(options).number.float({ min: 0, max: 1 });

export const fakeExclusiveInt = (options?: Options): ExclusiveInt => ensureFaker(options).number.int({ min: 1, max: 9 });

export const fakeMinOnlyNumber = (options?: Options): MinOnlyNumber => ensureFaker(options).number.float({ min: 0 });

export const fakeMaxOnlyInt = (options?: Options): MaxOnlyInt => ensureFaker(options).number.int({ max: 999 });

export const fakeExclusiveFloat = (options?: Options): ExclusiveFloat => ensureFaker(options).number.float({ min: 0, max: 1 });

export const fakeExclusiveFloatNarrow = (options?: Options): ExclusiveFloatNarrow => ensureFaker(options).number.float({ min: 10.1, max: 10.2 });

export const fakeTags = (options?: Options): Tags => ensureFaker(options).helpers.multiple(() => ensureFaker(options).string.sample());

export const fakeTagList = (options?: Options): TagList => ensureFaker(options).helpers.multiple(() => ensureFaker(options).string.sample(), { count: { min: 1, max: 10 } });

export const fakeMinOnlyArray = (options?: Options): MinOnlyArray => ensureFaker(options).helpers.multiple(() => ensureFaker(options).number.int(), { count: { min: 3, max: 1000 } });

export const fakeMaxOnlyArray = (options?: Options): MaxOnlyArray => ensureFaker(options).helpers.multiple(() => ensureFaker(options).string.sample(), { count: { min: 0, max: 5 } });

export const fakeDefaultString = (options?: Options): DefaultString => resolveCondition(options?.useDefault ?? false, ensureFaker(options)) ? 'unknown' : ensureFaker(options).string.sample();

export const fakeDefaultInt = (options?: Options): DefaultInt => resolveCondition(options?.useDefault ?? false, ensureFaker(options)) ? 0 : ensureFaker(options).number.int();

export const fakeDefaultBool = (options?: Options): DefaultBool => resolveCondition(options?.useDefault ?? false, ensureFaker(options)) ? true : ensureFaker(options).datatype.boolean();

export const fakeDefaultOverridesConstraints = (options?: Options): DefaultOverridesConstraints => resolveCondition(options?.useDefault ?? false, ensureFaker(options)) ? 42 : ensureFaker(options).number.int({ min: 1, max: 100 });

export const fakeNullableString = (options?: Options): NullableString => ensureFaker(options).datatype.boolean() ? ensureFaker(options).string.sample() : null;

export const fakeNullableInt = (options?: Options): NullableInt => ensureFaker(options).datatype.boolean() ? ensureFaker(options).number.int() : null;

export const fakeObjectWithDefaultProp = (options?: Options): ObjectWithDefaultProp => ({
    name: ensureFaker(options).string.sample(),
    ...!resolveCondition(options?.includeOptional ?? true, ensureFaker(options)) ? {} : { status: resolveCondition(options?.useDefault ?? false, ensureFaker(options)) ? 'active' : ensureFaker(options).string.sample() }
});

export const fakeUserProfile = (options?: Options): UserProfile => ({
    id: ensureFaker(options).number.int(),
    name: ensureFaker(options).string.sample(),
    ...!resolveCondition(options?.includeOptional ?? true, ensureFaker(options)) ? {} : { bio: ensureFaker(options).lorem.sentence() },
    ...!resolveCondition(options?.includeOptional ?? true, ensureFaker(options)) ? {} : { age: ensureFaker(options).number.int({ min: 1, max: 120 }) }
});

export const fakeTag = (options?: Options): Tag => ({
    id: ensureFaker(options).number.int(),
    label: ensureFaker(options).string.sample()
});

export const fakePet = (options?: Options): Pet => ({
    id: ensureFaker(options).string.uuid(),
    name: ensureFaker(options).string.sample(),
    ...!resolveCondition(options?.includeOptional ?? true, ensureFaker(options)) ? {} : { age: ensureFaker(options).number.int({ min: 1, max: 120 }) },
    ...!resolveCondition(options?.includeOptional ?? true, ensureFaker(options)) ? {} : { tag: fakeTag(options) }
});

export const fakeError = (options?: Options): Error => ({
    code: ensureFaker(options).number.int(),
    message: ensureFaker(options).string.sample()
});

export const fakeAddress = (options?: Options): Address => ({
    street: ensureFaker(options).location.streetAddress(),
    zip: fakeZipCode(options)
});

export const fakePerson = (options?: Options): Person => ({
    name: fakeShortName(options),
    email: fakeEmail(options),
    ...!resolveCondition(options?.includeOptional ?? true, ensureFaker(options)) ? {} : { address: fakeAddress(options) }
});

export const fakePersonList = (options?: Options): PersonList => ensureFaker(options).helpers.multiple(() => fakePerson(options), { count: { min: 1, max: 20 } });

export const fakePetList = (options?: Options): PetList => ensureFaker(options).helpers.multiple(() => fakePet(options));

export const fakeTeam = (options?: Options): Team => ({
    lead: fakePerson(options),
    config: fakeObjectWithDefaultProp(options)
});

export const fakePetWithOwner = (options?: Options): PetWithOwner => ({
    ...fakePet(options),
    ...{
        owner: ensureFaker(options).string.sample()
    }
});

export const fakePersonProfile = (options?: Options): PersonProfile => ({
    firstName: ensureFaker(options).person.firstName(),
    last_name: ensureFaker(options).person.lastName(),
    email: ensureFaker(options).internet.email(),
    phone: ensureFaker(options).phone.number(),
    age: ensureFaker(options).number.int({ min: 1, max: 120 }),
    city: ensureFaker(options).location.city(),
    postalCode: ensureFaker(options).location.zipCode(),
    bio: ensureFaker(options).lorem.sentence(),
    website: ensureFaker(options).internet.url(),
    zipCode: ensureFaker(options).helpers.fromRegExp('^\\d{5}$'),
    username: ensureFaker(options).internet.username(),
    someRandomField: ensureFaker(options).string.sample()
});

export const fakePersonWithConstraints = (options?: Options): PersonWithConstraints => ({
    age: ensureFaker(options).number.int({ min: 18, max: 120 }),
    ...!resolveCondition(options?.includeOptional ?? true, ensureFaker(options)) ? {} : { seniorAge: ensureFaker(options).number.int({ min: 65, max: 100 }) }
});

export const fakeUser = (options?: Options): User => ({
    name: ensureFaker(options).person.fullName(),
    email: ensureFaker(options).internet.email()
});

export const fakeCompany = (options?: Options): Company => ({
    name: ensureFaker(options).company.name()
});

export const fakeConfig = (options?: Options): Config => ({
    name: ensureFaker(options).string.sample()
});

export const fakeDocument = (options?: Options): Document => ({
    id: ensureFaker(options).string.uuid(),
    _id: ensureFaker(options).string.uuid(),
    numericId: ensureFaker(options).number.int()
});

export const fakeListPetsResponse = (options?: Options): ListPetsResponse => ensureFaker(options).helpers.multiple(() => fakePet(options));

export const fakeCreatePetResponse201 = (options?: Options): CreatePetResponses[201] => fakePet(options);

export const fakeCreatePetResponse204 = (): CreatePetResponses[204] => undefined;

export const fakeDeletePetResponse204 = (): DeletePetResponses[204] => undefined;

export const fakeDeletePetResponse404 = (options?: Options): DeletePetErrors[404] => fakeError(options);

export const fakeGetPetResponse200 = (options?: Options): GetPetResponses[200] => fakePet(options);

export const fakeGetPetResponse404 = (options?: Options): GetPetErrors[404] => fakeError(options);

export const fakeHealthCheckResponse = (options?: Options): HealthCheckResponse => ensureFaker(options).string.sample();
