// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type PersonProfile = {
    firstName: string;
    last_name: string;
    email: string;
    phone: string;
    age: number;
    city: string;
    postalCode: string;
    bio: string;
    website: string;
    zipCode: string;
    username: string;
    someRandomField: string;
};

export type PersonWithConstraints = {
    age: number;
    seniorAge?: number;
};

export type User = {
    name: string;
    email: string;
};

export type Company = {
    name: string;
};

export type Config = {
    name: string;
};

export type Document = {
    id: string;
    _id: string;
    numericId: number;
};
