// This file is auto-generated by @hey-api/openapi-ts

import { http, type HttpHandler, HttpResponse, type HttpResponseResolver, type RequestHandlerOptions } from 'msw';

import type { ApiVVersionODataControllerCountResponses, CallWithDuplicateResponsesResponses, CallWithNoContentResponseResponses, CallWithParametersData, CallWithResponseAndNoContentResponseResponses, CallWithResponsesResponses, CallWithResultFromHeaderResponses, CallWithWeirdParameterNamesData, ComplexParamsData, ComplexParamsResponses, ComplexTypesResponses, DeleteFooData3, DummyAResponses, DummyBResponses, FileResponseData, FileResponseResponses, GetApiVbyApiVersionSimpleOperationData, GetApiVbyApiVersionSimpleOperationResponses, GetCallWithOptionalParamData, ImportData, ImportResponses, MultipartRequestData, MultipartResponseResponses, NonAsciiæøåÆøÅöôêÊ字符串Responses, PostApiVbyApiVersionFormDataData, PostApiVbyApiVersionRequestBodyData, PostCallWithOptionalParamData, PostCallWithOptionalParamResponses, PutWithFormUrlEncodedData, TestErrorCodeResponses, TypesData, TypesResponses, UploadFileData, UploadFileResponses } from './types.gen';

const toMswPath = (path: string, baseUrl: string) => `${baseUrl}${path.replace(/\{([^}]+)\}/g, ':$1')}`;

const resolveToNull = () => new HttpResponse(null);

type ToResponseUnion<T> = {
    [K in Extract<keyof T, number>]: {
        status: K;
        result: T[K];
    };
}[Extract<keyof T, number>];

type StringifyPathParams<T> = {
    [K in keyof T]-?: string | ReadonlyArray<string>;
};

export type SingleHandlerFactories = {
    export: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    patchApiVbyApiVersionNoTag: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    import: (responseOrResolver: ToResponseUnion<ImportResponses> | HttpResponseResolver<never, ImportData['body']>, options?: RequestHandlerOptions) => HttpHandler;
    fooWow: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    apiVVersionODataControllerCount: (responseOrResolver: ToResponseUnion<ApiVVersionODataControllerCountResponses> | HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    getApiVbyApiVersionSimpleOperation: (responseOrResolver: ToResponseUnion<GetApiVbyApiVersionSimpleOperationResponses> | HttpResponseResolver<StringifyPathParams<NonNullable<GetApiVbyApiVersionSimpleOperationData['path']>>, never>, options?: RequestHandlerOptions) => HttpHandler;
    deleteCallWithoutParametersAndResponse: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    getCallWithoutParametersAndResponse: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    headCallWithoutParametersAndResponse: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    optionsCallWithoutParametersAndResponse: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    patchCallWithoutParametersAndResponse: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    postCallWithoutParametersAndResponse: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    putCallWithoutParametersAndResponse: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    deleteFoo: (responseOrResolver?: HttpResponseResolver<StringifyPathParams<NonNullable<DeleteFooData3['path']>>, never>, options?: RequestHandlerOptions) => HttpHandler;
    callWithDescriptions: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    deprecatedCall: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    callWithParameters: (responseOrResolver?: HttpResponseResolver<StringifyPathParams<NonNullable<CallWithParametersData['path']>>, CallWithParametersData['body']>, options?: RequestHandlerOptions) => HttpHandler;
    callWithWeirdParameterNames: (responseOrResolver?: HttpResponseResolver<StringifyPathParams<NonNullable<CallWithWeirdParameterNamesData['path']>>, CallWithWeirdParameterNamesData['body']>, options?: RequestHandlerOptions) => HttpHandler;
    getCallWithOptionalParam: (responseOrResolver?: HttpResponseResolver<never, GetCallWithOptionalParamData['body']>, options?: RequestHandlerOptions) => HttpHandler;
    postCallWithOptionalParam: (responseOrResolver: ToResponseUnion<PostCallWithOptionalParamResponses> | HttpResponseResolver<never, PostCallWithOptionalParamData['body']>, options?: RequestHandlerOptions) => HttpHandler;
    postApiVbyApiVersionRequestBody: (responseOrResolver?: HttpResponseResolver<never, PostApiVbyApiVersionRequestBodyData['body']>, options?: RequestHandlerOptions) => HttpHandler;
    postApiVbyApiVersionFormData: (responseOrResolver?: HttpResponseResolver<never, PostApiVbyApiVersionFormDataData['body']>, options?: RequestHandlerOptions) => HttpHandler;
    callWithDefaultParameters: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    callWithDefaultOptionalParameters: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    callToTestOrderOfParams: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    duplicateName: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    duplicateName2: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    duplicateName3: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    duplicateName4: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    callWithNoContentResponse: (responseOrResolver?: ToResponseUnion<CallWithNoContentResponseResponses> | HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    callWithResponseAndNoContentResponse: (responseOrResolver: ToResponseUnion<CallWithResponseAndNoContentResponseResponses> | HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    dummyA: (responseOrResolver: ToResponseUnion<DummyAResponses> | HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    dummyB: (responseOrResolver?: ToResponseUnion<DummyBResponses> | HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    callWithResponse: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    callWithDuplicateResponses: (responseOrResolver: ToResponseUnion<CallWithDuplicateResponsesResponses> | HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    callWithResponses: (responseOrResolver: ToResponseUnion<CallWithResponsesResponses> | HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    collectionFormat: (responseOrResolver?: HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    types: (responseOrResolver: ToResponseUnion<TypesResponses> | HttpResponseResolver<StringifyPathParams<NonNullable<TypesData['path']>>, never>, options?: RequestHandlerOptions) => HttpHandler;
    uploadFile: (responseOrResolver: ToResponseUnion<UploadFileResponses> | HttpResponseResolver<StringifyPathParams<NonNullable<UploadFileData['path']>>, UploadFileData['body']>, options?: RequestHandlerOptions) => HttpHandler;
    fileResponse: (responseOrResolver: ToResponseUnion<FileResponseResponses> | HttpResponseResolver<StringifyPathParams<NonNullable<FileResponseData['path']>>, never>, options?: RequestHandlerOptions) => HttpHandler;
    complexTypes: (responseOrResolver: ToResponseUnion<ComplexTypesResponses> | HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    multipartResponse: (responseOrResolver: ToResponseUnion<MultipartResponseResponses> | HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    multipartRequest: (responseOrResolver?: HttpResponseResolver<never, MultipartRequestData['body']>, options?: RequestHandlerOptions) => HttpHandler;
    complexParams: (responseOrResolver: ToResponseUnion<ComplexParamsResponses> | HttpResponseResolver<StringifyPathParams<NonNullable<ComplexParamsData['path']>>, ComplexParamsData['body']>, options?: RequestHandlerOptions) => HttpHandler;
    callWithResultFromHeader: (responseOrResolver?: ToResponseUnion<CallWithResultFromHeaderResponses> | HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    testErrorCode: (responseOrResolver?: ToResponseUnion<TestErrorCodeResponses> | HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    nonAsciiæøåÆøÅöôêÊ字符串: (responseOrResolver: ToResponseUnion<NonAsciiæøåÆøÅöôêÊ字符串Responses> | HttpResponseResolver, options?: RequestHandlerOptions) => HttpHandler;
    putWithFormUrlEncoded: (responseOrResolver?: HttpResponseResolver<never, PutWithFormUrlEncodedData['body']>, options?: RequestHandlerOptions) => HttpHandler;
};

export type MswHandlerFactory = {
    of: SingleHandlerFactories;
};

export const createMswHandlerFactory = (config?: {
    baseUrl?: string;
}): MswHandlerFactory => {
    const baseUrl = config?.baseUrl ?? 'http://localhost:3000/base';
    const of: SingleHandlerFactories = {
        export: (res, options) => http.get(toMswPath('/api/v{api-version}/no+tag', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        patchApiVbyApiVersionNoTag: (res, options) => http.patch(toMswPath('/api/v{api-version}/no+tag', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        import: (res, options) => http.post(toMswPath('/api/v{api-version}/no+tag', baseUrl), typeof res === 'object' && res.status ? () => HttpResponse.json(res.result ?? null, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options),
        fooWow: (res, options) => http.put(toMswPath('/api/v{api-version}/no+tag', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        apiVVersionODataControllerCount: (res, options) => http.get(toMswPath('/api/v{api-version}/simple/$count', baseUrl), typeof res === 'object' && res.status ? () => HttpResponse.json(res.result ?? null, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options),
        getApiVbyApiVersionSimpleOperation: (res, options) => http.get(toMswPath('/api/v{api-version}/simple:operation', baseUrl), typeof res === 'object' && res.status ? () => HttpResponse.json(res.result ?? null, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options),
        deleteCallWithoutParametersAndResponse: (res, options) => http.delete(toMswPath('/api/v{api-version}/simple', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        getCallWithoutParametersAndResponse: (res, options) => http.get(toMswPath('/api/v{api-version}/simple', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        headCallWithoutParametersAndResponse: (res, options) => http.head(toMswPath('/api/v{api-version}/simple', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        optionsCallWithoutParametersAndResponse: (res, options) => http.options(toMswPath('/api/v{api-version}/simple', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        patchCallWithoutParametersAndResponse: (res, options) => http.patch(toMswPath('/api/v{api-version}/simple', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        postCallWithoutParametersAndResponse: (res, options) => http.post(toMswPath('/api/v{api-version}/simple', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        putCallWithoutParametersAndResponse: (res, options) => http.put(toMswPath('/api/v{api-version}/simple', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        deleteFoo: (res, options) => http.delete(toMswPath('/api/v{api-version}/foo/{foo_param}/bar/{BarParam}', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        callWithDescriptions: (res, options) => http.post(toMswPath('/api/v{api-version}/descriptions', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        deprecatedCall: (res, options) => http.post(toMswPath('/api/v{api-version}/parameters/deprecated', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        callWithParameters: (res, options) => http.post(toMswPath('/api/v{api-version}/parameters/{parameterPath}', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        callWithWeirdParameterNames: (res, options) => http.post(toMswPath('/api/v{api-version}/parameters/{parameter.path.1}/{parameter-path-2}/{PARAMETER-PATH-3}', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        getCallWithOptionalParam: (res, options) => http.get(toMswPath('/api/v{api-version}/parameters', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        postCallWithOptionalParam: (res, options) => http.post(toMswPath('/api/v{api-version}/parameters', baseUrl), typeof res === 'object' && res.status ? () => HttpResponse.json(res.result ?? null, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options),
        postApiVbyApiVersionRequestBody: (res, options) => http.post(toMswPath('/api/v{api-version}/requestBody', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        postApiVbyApiVersionFormData: (res, options) => http.post(toMswPath('/api/v{api-version}/formData', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        callWithDefaultParameters: (res, options) => http.get(toMswPath('/api/v{api-version}/defaults', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        callWithDefaultOptionalParameters: (res, options) => http.post(toMswPath('/api/v{api-version}/defaults', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        callToTestOrderOfParams: (res, options) => http.put(toMswPath('/api/v{api-version}/defaults', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        duplicateName: (res, options) => http.delete(toMswPath('/api/v{api-version}/duplicate', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        duplicateName2: (res, options) => http.get(toMswPath('/api/v{api-version}/duplicate', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        duplicateName3: (res, options) => http.post(toMswPath('/api/v{api-version}/duplicate', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        duplicateName4: (res, options) => http.put(toMswPath('/api/v{api-version}/duplicate', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        callWithNoContentResponse: (res, options) => http.get(toMswPath('/api/v{api-version}/no-content', baseUrl), typeof res === 'object' && res.status ? () => new HttpResponse(res.result ?? null, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options),
        callWithResponseAndNoContentResponse: (res, options) => http.get(toMswPath('/api/v{api-version}/multiple-tags/response-and-no-content', baseUrl), typeof res === 'object' && res.status ? () => HttpResponse.json(res.result ?? null, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options),
        dummyA: (res, options) => http.get(toMswPath('/api/v{api-version}/multiple-tags/a', baseUrl), typeof res === 'object' && res.status ? () => HttpResponse.json(res.result ?? null, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options),
        dummyB: (res, options) => http.get(toMswPath('/api/v{api-version}/multiple-tags/b', baseUrl), typeof res === 'object' && res.status ? () => new HttpResponse(res.result ?? null, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options),
        callWithResponse: (res, options) => http.get(toMswPath('/api/v{api-version}/response', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        callWithDuplicateResponses: (res, options) => http.post(toMswPath('/api/v{api-version}/response', baseUrl), typeof res === 'object' && res.status ? () => HttpResponse.json(res.result ?? null, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options),
        callWithResponses: (res, options) => http.put(toMswPath('/api/v{api-version}/response', baseUrl), typeof res === 'object' && res.status ? () => HttpResponse.json(res.result ?? null, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options),
        collectionFormat: (res, options) => http.get(toMswPath('/api/v{api-version}/collectionFormat', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        types: (res, options) => http.get(toMswPath('/api/v{api-version}/types', baseUrl), typeof res === 'object' && res.status ? () => HttpResponse.json(res.result ?? null, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options),
        uploadFile: (res, options) => http.post(toMswPath('/api/v{api-version}/upload', baseUrl), typeof res === 'object' && res.status ? () => HttpResponse.json(res.result ?? null, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options),
        fileResponse: (res, options) => http.get(toMswPath('/api/v{api-version}/file/{id}', baseUrl), typeof res === 'object' && res.status ? () => new HttpResponse(res.result as any, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options),
        complexTypes: (res, options) => http.get(toMswPath('/api/v{api-version}/complex', baseUrl), typeof res === 'object' && res.status ? () => HttpResponse.json(res.result ?? null, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options),
        multipartResponse: (res, options) => http.get(toMswPath('/api/v{api-version}/multipart', baseUrl), typeof res === 'object' && res.status ? () => HttpResponse.json(res.result ?? null, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options),
        multipartRequest: (res, options) => http.post(toMswPath('/api/v{api-version}/multipart', baseUrl), typeof res === 'function' ? res : resolveToNull, options),
        complexParams: (res, options) => http.put(toMswPath('/api/v{api-version}/complex/{id}', baseUrl), typeof res === 'object' && res.status ? () => HttpResponse.json(res.result ?? null, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options),
        callWithResultFromHeader: (res, options) => http.post(toMswPath('/api/v{api-version}/header', baseUrl), typeof res === 'object' && res.status ? () => new HttpResponse(res.result ?? null, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options),
        testErrorCode: (res, options) => http.post(toMswPath('/api/v{api-version}/error', baseUrl), typeof res === 'object' && res.status ? () => new HttpResponse(res.result ?? null, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options),
        nonAsciiæøåÆøÅöôêÊ字符串: (res, options) => http.post(toMswPath('/api/v{api-version}/non-ascii-æøåÆØÅöôêÊ字符串', baseUrl), typeof res === 'object' && res.status ? () => HttpResponse.json(res.result ?? null, { status: res.status }) : typeof res === 'function' ? res : resolveToNull, options),
        putWithFormUrlEncoded: (res, options) => http.put(toMswPath('/api/v{api-version}/non-ascii-æøåÆØÅöôêÊ字符串', baseUrl), typeof res === 'function' ? res : resolveToNull, options)
    };
    return { of };
};
