// This file is auto-generated by @hey-api/openapi-ts

import { faker, type Faker } from '@faker-js/faker';

import type { Company, Config, PersonProfile, PersonWithConstraints, User } from '../types.gen';

export type Options = {
    faker?: Faker;
    /**
     * Whether to include optional properties.
     * Provide a number between 0 and 1 to randomly include based on that probability.
     * @default true
     */
    includeOptional?: boolean | number;
    /**
     * Whether to use schema default values instead of generating fake data.
     * Provide a number between 0 and 1 to randomly use defaults based on that probability.
     * @default false
     */
    useDefault?: boolean | number;
};

const resolveCondition = (condition: boolean | number, faker: Faker): boolean => condition === true || typeof condition === 'number' && faker.datatype.boolean({ probability: condition });

const ensureFaker = (options?: Options): Faker => options?.faker ?? faker;

export const fakePersonProfile = (options?: Options): PersonProfile => ({
    firstName: ensureFaker(options).person.firstName(),
    last_name: ensureFaker(options).person.lastName(),
    email: ensureFaker(options).internet.email(),
    phone: ensureFaker(options).phone.number(),
    age: ensureFaker(options).number.int({ min: 1, max: 120 }),
    city: ensureFaker(options).location.city(),
    postalCode: ensureFaker(options).location.zipCode(),
    bio: ensureFaker(options).lorem.sentence(),
    website: ensureFaker(options).internet.url(),
    zipCode: ensureFaker(options).helpers.fromRegExp('^\\d{5}$'),
    username: ensureFaker(options).internet.username(),
    someRandomField: ensureFaker(options).string.sample()
});

export const fakePersonWithConstraints = (options?: Options): PersonWithConstraints => ({
    age: ensureFaker(options).number.int({ min: 18, max: 120 }),
    ...!resolveCondition(options?.includeOptional ?? true, ensureFaker(options)) ? {} : { seniorAge: ensureFaker(options).number.int({ min: 65, max: 100 }) }
});

export const fakeUser = (options?: Options): User => ({
    name: ensureFaker(options).person.fullName(),
    email: ensureFaker(options).internet.email()
});

export const fakeCompany = (options?: Options): Company => ({
    name: ensureFaker(options).company.name()
});

export const fakeConfig = (options?: Options): Config => ({
    name: ensureFaker(options).string.sample()
});
