// This file is auto-generated by @hey-api/openapi-ts

export type { Animal, Cat, Circle, ClientOptions, Dog, NullablePetOrTag, Pet, PetOrTag, PetWithOwner, Shape, Square, StringOrNumber, Tag } from './types.gen';
