// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Pet = {
    name: string;
    age: number;
};

export type Tag = {
    id: number;
    label: string;
};

export type PetOrTag = Pet | Tag;

export type StringOrNumber = string | number;

export type NullablePetOrTag = Pet | Tag | null;

export type PetWithOwner = Pet & {
    owner: string;
};

export type Circle = {
    kind: string;
    radius: number;
};

export type Square = {
    kind: string;
    side: number;
};

export type Shape = ({
    kind: 'Circle';
} & Circle) | ({
    kind: 'Square';
} & Square);

export type Dog = {
    type: string;
    bark: boolean;
};

export type Cat = {
    type: string;
    purr: boolean;
};

export type Animal = ({
    type: 'dog';
} & Dog) | ({
    type: 'cat';
} & Cat);
