// This file is auto-generated by @hey-api/openapi-ts

export type { Active, Anything, ClientOptions, Nothing, NumericEnum, Pet, PetList, PetOrTag, Price, Quantity, StatusWithNull, StringOrNumber, Tag, Tags } from './types.gen';
