// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Price = number;

export type Quantity = number;

export type Active = boolean;

export type Nothing = null;

export type Anything = unknown;

export type StatusWithNull = 'active' | 'inactive' | null;

export type NumericEnum = 1 | 2 | 3;

export type Tags = Array<string>;

export type Pet = {
    name: string;
    tag?: Tag;
};

export type Tag = {
    id: number;
    label: string;
};

export type PetOrTag = Pet | Tag;

export type StringOrNumber = string | number;

export type PetList = Array<Pet>;
